### PR TITLE
Tidy indents in output, move simple styles from JSON to JS, deduplicate simple style code

### PR DESCRIPTION
**Pull request by tomchadwin**
#138
Complete for simple styles - more to follow.

Please test

### CODE REVIEW

**Comment by tomchadwin** [comment]
This is a big one - please test if you can

**Comment by mtravis** [comment]
just tested with combo of flat files, postgis and wfs. All seems fine to me. Anything in particular i should be looking for.

2015-03-25 18_58_14-qgis2leaf webmap

**Comment by riccardoklinger** [comment]
tested with sample test files in test_data folder and its project received a crash for raster export:
Traceback (most recent call last):
  File "C:/Users/rikl/.qgis2/python/plugins\qgis2leaf\qgis2leafdialog.py", line 297, in export2leaf
    qgis2leaf_exec(self.outFileName, self.basemapName, self.basemapMeta, self.basemapAddress, self.width, self.height, self.extent, self.full_screen, self.layer_list, self.visible, self.opacity, self.encode2JSON,self.createcluster, self.webpage_name, self.webmap_head,self.webmap_subhead, self.legend,self.locate,self.address, self.precision, self.labels, self.labelshover, self.matchCRS, self.selected)
  File "C:/Users/rikl/.qgis2/python/plugins\qgis2leaf\qgis2leaf_exec.py", line 518, in qgis2leaf_exec
    dst_ds = driver.CreateCopy( out_raster, src_ds, 0 )
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\osgeo\gdal.py", line 395, in CreateCopy
    return _gdal.Driver_CreateCopy(self, *args, **kwargs)
ValueError: Received a NULL pointer.

But this is a known error. tested with QGIS 2.8.1 on Win 64
Tests with the other layers was successfull.

HTML output looks very tidy! Great work @tomchadwin !!!

**Comment by tomchadwin** [comment]
@mtravis Crashes and incorrect styles, I guess.

@riccardoklinger Not all code has been tidied (eg clustering, rasters), so there's more to do. I also want to comment the output code fully.

But I'm pleased it seems to be working well so far. More to come soon, I hope.

**Comment by tomchadwin** [comment]
@mtravis And untidy output code.

**Comment by mtravis** [comment]
Looks loads tidier to me :)

**Comment by tomchadwin** [comment]
@mtravis I didn't check that this hasn't reintroduced the issue where all popups wrongly contain the attribute data from one single feature.

**Comment by mtravis** [comment]
@tomchadwin all good there!

**Comment by tomchadwin** [comment]
@mtravis Great. I'll try to break the back of categorized and graduated today and tomorrow.

**Pull request merged**
