### PR TITLE
 WMS polygons with fill style: no brush 

### PR DESCRIPTION
**Pull request by tomchadwin**
#187

### CODE REVIEW

**Comment by riccardoklinger** [comment]
Hi @tomchadwin , just saw this merge request. You think it's save?!

**Comment by tomchadwin** [comment]
I'm confused - hasn't this been merged already?

**Comment by riccardoklinger** [comment]
Nope as it is still open on github...

**Comment by riccardoklinger** [comment]
Or am I wrong...

**Comment by tomchadwin** [comment]
Looks merged and closed to me:

Riccardo Klinger riccardoklinger merged commit a3c9db0 into Geolicious:master from tomchadwin:master on Dec 18 2014 

Riccardo Klinger riccardoklinger closed this on Dec 18 2014

**Pull request merged**
